name: setup
runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/cache@v3
      id: cache
      with:
        key: ${{ runner.os }}-${{ hashFiles('lock.json') }}-${{ hashFiles('Makefile') }}-${{ hashFiles('.github/actions/setup/action.yml') }}
        path: |
          bin
          .deno
          /opt/hostedtoolcache/deno/

    - if: steps.cache.outputs.cache-hit != 'true'
      run: make install
      shell: bash
