name: setup
runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/cache@v3
      id: cache
      with:
        key: ${{ runner.os }}-${{ hashFiles('lock.json') }}-${{ hashFiles('Makefile') }}
        path: |
          ~/runner/work/automations/automations/bin
          ~/runner/work/automations/automations/.deno
    - if: ${{ steps.cache.outputs.cache-hit == 'false' }}
      run: make install
      shell: bash
